language: java

cache:
  directories:
  - ~/.m2

git:
  depth: 1

branches:
  only:
    - master

install:
  mvn -T 1C install -Dmaven.test.skip -B -fae -s settings.xml

script:
  mvn -T 1C test -B -fae -s settings.xml
